### ISSUE TITLE
Worker mode in `ts_project` is flaky. 

### ISSUE THREAD

**Issue by bhavitsharma** [aspect-build/rules_ts#128]
The worker-mode is flaky in the `ts_project` rule. It arbitrarily fails with the following error:
(The error disappears if I wipe the bazel's cache and start from a clean state. However if I change the dependency of `relicx-common-ui-safe` package, then the error appears again)

```
WARNING: Remote Cache: Expected output ts/relicx-common-ui-safe/ui-safe.tsbuildinfo was not created locally.
java.io.IOException: Expected output ts/relicx-common-ui-safe/ui-safe.tsbuildinfo was not created locally.
        at com.google.devtools.build.lib.remote.RemoteExecutionService.lambda$buildUploadManifestAsync$6(RemoteExecutionService.java:1112)
        at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)
        at com.google.devtools.build.lib.remote.RemoteExecutionService.buildUploadManifest(RemoteExecutionService.java:1134)
        at com.google.devtools.build.lib.remote.RemoteExecutionService.uploadOutputs(RemoteExecutionService.java:1187)
        at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:192)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:151)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:108)
        at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
        at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:68)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:328)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:907)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1076)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1031)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:492)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
ERROR: /relicx/ts/relicx-common-ui-safe/BUILD:27:7: output 'ts/relicx-common-ui-safe/ui-safe.tsbuildinfo' was not created
ERROR: /relicx/ts/relicx-common-ui-safe/BUILD:27:7: Compiling TypeScript project //ts/relicx-common-ui-safe:ui-safe_typings [tsc -p ts/relicx-common-ui-safe/tsconfig_ui-safe.json] failed: not all outputs were created or valid
ERROR: /relicx/ts/relicx-common-ui-safe/BUILD:27:7 Copying files to directory failed: not all outputs were created or valid
```

I have disabled the support_workers mode as a workaround. Any idea why it could be failing?

`rules_ts`: 1.0.0
`bazel`: 5.2.0

**Comment by bhavitsharma** [comment]
Unsure how to reproduce it reliably.

**Comment by thesayyn** [comment]
This is an interesting one. Are you using remote execution or just remote cache?  I'd be happy to take a look if you could provide a minimal repro. I am fine with it failing randomly as long as i have the minimal `BUILD` file 

> However if I change the dependency of `relicx-common-ui-safe` package, then the error appears again)

Probably this is how you reproduce it? If it fails 2 times out of 5 then it's good enough for me to work on.

**Comment by bhavitsharma** [comment]
Sure, I'll try to create a minimal reproduction repo for it in the next 12 hours

**Comment by thesayyn** [comment]
Hey @bhavitsharma. following up on this. by any chance, were you able to put up a repro?

**Comment by bhavitsharma** [comment]
Apologies for the response. The repro should be something like.
/ -> root
/ts/package.json
/ts/pnpm.yaml
/ts/BUILD
/ts/project_a
/ts/project_b

`project_a` depends on `project_b` via `npm_link_package` in `/ts/BUILD`.

Now changing some login in project_b leads to this error sometimes

**Comment by codesuki** [comment]
Just chiming in to say that I have a similar issue. 
Everything was fine with 1 `ts_project`. Adding two and a dependency between resulted in an error like this:
```client.js' is not under 'rootDir' 'web/src/'. 'rootDir' is expected to contain all source files.```
Probably similar to the above except that I don't use `npm_link_package`. I oriented myself at the `examples/ts_project_deps`. Disabling the worker for the depending project fixes this.

**Comment by thesayyn** [comment]
My guess is that two `ts_project` targets are using the same program leading to flakiness. I'd be willing to work on this if someone could provide a repro that I can work with.

**Comment by matthewjh** [comment]
I also have this problem.

**Comment by bhavitsharma** [comment]
I tried the latest rules: [v1.0.0-rc4](https://github.com/aspect-build/rules_ts/releases/tag/v1.0.0-rc4) with PR: https://github.com/aspect-build/rules_ts/pull/169

And it didn't fix the issue.

**Comment by thesayyn** [comment]
> Do you have any idea what the bug could be about

tsc is ran slightly differently as a worker. 
by design `tsc --watch` won't emit files that haven't changed in the subsequent builds but bazel requires workers to emit everything every time. to account for this ts_project_worker keeps track of what has been changed and needs to be remitted. probably, something wrong here; https://github.com/aspect-build/rules_ts/blob/ab68b6bf873c3de66bf323be6c8ba3791b180d6e/ts/private/ts_project_worker.js#L263-L328
