### ISSUE TITLE
[Bug]: ts_project can not have a `select` statement in srcs or deps

### ISSUE THREAD

**Issue by mattem** [aspect-build/rules_ts#220]
### What happened?

It's not possible to use a `select` in the `srcs` or `deps` of a `ts_project` rule. 

Apply the patch below and run `bazel build //examples/transpiler:babel`, not the error:

```
ERROR: Traceback (most recent call last):
	File "/Users/matt/workspace/rules_ts/examples/transpiler/BUILD.bazel", line 28, column 11, in <toplevel>
		ts_project(
	File "/Users/matt/workspace/rules_ts/ts/defs.bzl", line 307, column 37, in ts_project
		js_outs = _lib.calculate_js_outs(srcs, out_dir, root_dir, allow_js, preserve_jsx, emit_declaration_only)
	File "/Users/matt/workspace/rules_ts/ts/private/ts_lib.bzl", line 206, column 22, in _calculate_js_outs
		return _out_paths(srcs, out_dir, root_dir, allow_js, exts)
	File "/Users/matt/workspace/rules_ts/ts/private/ts_lib.bzl", line 180, column 14, in _out_paths
		for f in srcs:
Error: type 'select' is not iterable
```

This is made double tricky to hold as #219 prevents placing the `select` on a `filegroup` and adding that to `ts_project`

### Version

HEAD

### How to reproduce

```shell
diff --git a/examples/transpiler/BUILD.bazel b/examples/transpiler/BUILD.bazel
index d9e1ede..74e6fc9 100644
--- a/examples/transpiler/BUILD.bazel
+++ b/examples/transpiler/BUILD.bazel
@@ -18,11 +18,18 @@ write_file(
     ],
 )

+config_setting(
+    name = "stamp",
+    values = {"stamp": "true"},
+)
+
 # Runs babel to transpile ts -> js
 # and tsc to type-check
 ts_project(
     name = "babel",
-    srcs = ["big.ts"],
+    srcs = select({
+        ":stamp": ["big.ts"],
+    }),
     declaration = True,
     out_dir = "build-babel",
     source_map = True,
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by arrdem** [comment]
Closing since there appears to be a workaround available.
